name: trackable
description: Marker interfaces for trackable events and errors.
version: 1.0.1
repository: https://github.com/netglade/trackable

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.12.0
  nanoid2: ^2.0.1
  uuid: ^4.4.2

dev_dependencies:
  netglade_analysis: ^11.0.0
  test: ^1.24.0
